Adding capability to update stack when ingress paths are updated.
awslabs/amazon-apigateway-ingress-controller pull request #15
Opened 2020-05-08 11:26 UTC by danushkaf

*Issue #, if available:*
Didn't create a github issue

*Description of changes:*
In the current version if we update ingress rules it will not update the stack. I have done below modifications to add that capability to current apigw ingress controller. I did this fix to make it usable to my current project. I thought of contributing with this so some one has same requirements it will be useful.
This works for both new paths and deleted paths.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-05-10 23:06 UTC, Magizhchi requested changes
Thanks for the contribution, this mostly looks good, just had a few questions.

2020-05-10 23:06 UTC, Magizhchi commented on pkg/controller/ingress/helpers.go
> +					if strings.HasPrefix(*apiItem.Path, path.Path) || strings.HasPrefix(path.Path, *apiItem.Path) {
Why check for a prefix here ?

2020-05-10 23:06 UTC, Magizhchi commented on pkg/controller/ingress/helpers.go
> +					return true
Can we move this logic into a package under here - https://github.com/awslabs/amazon-apigateway-ingress-controller/tree/master/pkg.

2020-05-10 23:06 UTC, Magizhchi commented on pkg/controller/ingress/helpers.go
> +			//To identity newly added paths
Why check separately for newly added and removed paths ?

2020-05-11 04:16 UTC, danushkaf commented on pkg/controller/ingress/helpers.go
> +					if strings.HasPrefix(*apiItem.Path, path.Path) || strings.HasPrefix(path.Path, *apiItem.Path) {
When we added rules in ingress, It is added to API GW with breakdown sub paths. So here we need to match subpaths with ingress rules. So when we are comparing existing API GW rules we have to check with prefix.

2020-05-11 04:17 UTC, danushkaf commented on pkg/controller/ingress/helpers.go
> +			//To identity newly added paths
Because logic is different for added paths and removed paths

2020-05-11 04:19 UTC, danushkaf commented on pkg/controller/ingress/helpers.go
> +					return true
This logic is specific to API GW rule checking. I guess you want to move it to some library. This method is created to check whether update CF stack is needed or not. Is there a reason to move it to there?

2020-05-17 17:02 UTC, closed without merging

2020-05-17 17:03 UTC, danushkaf commented
Will Open a PR with more advanced features